name:                reversible
version:             0.1.0.0
github:              "stefanbohne/reversible"
license:             BSD3
author:              "Stefan Bohne"
maintainer:          "stbohne@gmail.com"
copyright:           "2019 Stefan Bohne"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/thesis#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- lattices
- megaparsec
- text
- parser-combinators

library:
  source-dirs: src
  ghc-options:
  - -XFlexibleInstances
  - -XLambdaCase
  - -XMultiWayIf 
  - -XDatatypeContexts
  - -XOverlappingInstances
  - -XOverloadedStrings
  - -XGADTs
  - -XKindSignatures
  - -XExplicitForAll
  - -XTupleSections

executables:
  thesis-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -XOverlappingInstances
    - -XOverloadedStrings
    dependencies:
    - reversible
    - repline
    - haskeline

tests:
  thesis-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -XFlexibleInstances
    - -XLambdaCase
    - -XMultiWayIf 
    - -XDatatypeContexts
    - -XOverlappingInstances
    - -XOverloadedStrings
    - -XGADTs
    dependencies:
    - reversible
    - HTF
    build-tools:
    - cpphs:cpphs
